### ISSUE TITLE
Error: spawn EACCES at _errnoException (util.js:1022:11)

### ISSUE THREAD

**Issue by KarthikMuthuvel** [deek87/lamba-thumbnailer#1]
I got the below error from Cloudwatch logs when i triggered the lambda function form S3 PUT event.
Error: spawn EACCES
at _errnoException (util.js:1022:11)
at ChildProcess.spawn (internal/child_process.js:323:11)
at Object.exports.spawn (child_process.js:502:9)
at createThumbnail (/var/task/index.js:66:36)
at nextTask (/var/task/node_modules/async/dist/async.js:5324:14)
at Object.waterfall (/var/task/node_modules/async/dist/async.js:5334:5)
at exports.handler (/var/task/index.js:60:9)

Any idea ? how to resolve it ?

**Comment by deek87** [comment]
That seems like ffmpeg doesnt have execute access

can you try changing
line 66 
`var ffmpeg = child_process.spawn("ffmpeg", [`
to
`var ffmpeg = child_process.spawn("/tmp/ffmpeg", [`

**Comment by suravi999** [comment]
Change the 66th line and still issue is there...

**Comment by deek87** [comment]
@suravi999 Is this @KarthikMuthuvel  also your account?

If it is not please can you post your exact cloudwatch logs.

I will also need to your OS, and can you tell me the directory layout of the zip file

**Comment by KarthikMuthuvel** [comment]
> @suravi999 Is this @KarthikMuthuvel also your account?
> 
> If it is not please can you post your exact cloudwatch logs.
> 
> I will also need to your OS, and can you tell me the directory layout of the zip file

**Comment by KarthikMuthuvel** [comment]
> That seems like ffmpeg doesnt have execute access
> 
> can you try changing
> line 66
> `var ffmpeg = child_process.spawn("ffmpeg", [`
> to
> `var ffmpeg = child_process.spawn("/tmp/ffmpeg", [`

Hi Derek,

Thanks for the response. 
I was trying to change the permission of ffmpeg from windows OS. Later on i realized that ffmpeg is the binary for Linux and i did the permission changes from Linux EC2. Its working now. 
I have posted a new issue related to the size of the videos in your Original post. "https://concrete5.co.jp/blog/creating-video-thumbnails-aws-lambda-your-s3-bucket"

Thanks,
Karthik
