### ISSUE TITLE
thumbnails are created with size 0

### ISSUE THREAD

**Issue by ishener** [deek87/lamba-thumbnailer#2]
i created a function and uploaded with exactly the code in this repo. everything looks like it's working, and the thumbnail file is created, but it's size is 0 and it's obviously not good

1. do you have any idea what can cause this behavior?

2. is there any way to see the output of ffmpeg, maybe i'll see some hints there.

by the way, i tried running ffmpeg with exactly the same parameters on my local machine, and it works correctly.

**Comment by robwalkerco** [comment]
@ishener I was just getting this same issue, and I discovered it was as the video was less than 5 seconds long.

Try changing this to 1 second -
`"00:00:05", // time to take screenshot`

**Comment by ishener** [comment]
the issue was that the timeout for my lambda function was too low, and also the memory ran out. i  increased the timeout and memory and everything works
