### ISSUE TITLE
Error spawn EACCES

### ISSUE THREAD

**Issue by smillerk2** [deek87/lamba-thumbnailer#3]
I know this has been reported in an older issue but I'm not able to resolve it. I've tried Node 6.10 and Node 8.10 and also experimented with /tmp/ffmpeg and ffmeg as the path - to no avail. 

```
Error: spawn EACCES
at exports._errnoException (util.js:1018:11)
at ChildProcess.spawn (internal/child_process.js:319:11)
at Object.exports.spawn (child_process.js:378:9)
```
Directory structure of ZIP:

```
ffmpeg
index.js
node_modules\
package.json
```

Any ideas?

**Comment by deek87** [comment]
This is a windows issue with zipping up the files, is fixed with lambda layers
