### ISSUE TITLE
You are not authorized to perform: lambda:GetLayerVersion.

### ISSUE THREAD

**Issue by dotjiwa** [deek87/lamba-thumbnailer#4]
Hi there--

I am configuring a layer for my lambda function which exists in us-west-2. 

When adding this ARN: 
arn:aws:lambda:us-west-2:260572601982:layer:ffmpeg:1

And clicking Add, I get this error: 
You are not authorized to perform: lambda:GetLayerVersion.

Please advise/enable global permissions on the layer. Thanks!

**Comment by dotjiwa** [comment]
I was able to get around this by down-grading my lambda project from Node 12.x to 10.x, deploying the mentioned ffmpeg package (https://github.com/serverlesspub/ffmpeg-aws-lambda-layer), and going with a different code example all together : https://dev.to/benjaminadk/how-do-i-create-thumbnails-when-i-upload-a-video-aws-lambda-7l4 .

I know this github project was a predecessor to the aforementioned article, so credit to deek87 as well. Thanks. 

I hope this helps someone else. Cheers!

**Comment by philihp** [comment]
This appears to still be an issue. I am also on us-west-2, maybe the resource policy is restricting access?

<img width="891" alt="Screen Shot 2021-12-09 at 01 14 51" src="https://user-images.githubusercontent.com/1247668/145316547-24450856-3e82-4882-8e7d-c0282be0af3b.png">

I am logged in as an administrator, and I have also given myself the policy
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "LambdaYOLO",
            "Effect": "Allow",
            "Action": "lambda:*",
            "Resource": "*"
        }
    ]
}
```
