### ISSUE TITLE
Unable to change the export time

### ISSUE THREAD

**Issue by EnricoNapolitan** [deek87/lamba-thumbnailer#7]
I am using the Thumbnail property "time" as said in the documentation:
```javascript
t.createThumbnail({
  ...
  time: "00:00:02",
  ...
})
```
but the export time isn't changing, the lib always uses the default value "00:00:10".
I think the problem is: the input var is called "time" but then in the lib is used "timestamp".

**Comment by deek87** [comment]
fixed in 2.0.1
sorry for the late reply didnt get notification for this
